### PR TITLE
Remove filledDebtOrders and investments from localStorage

### PR DESCRIPTION
**Pull request by jmul-dev**
https://www.pivotaltracker.com/story/show/156831664

### CODE REVIEW

**Comment by jmul-dev** [comment]
I also store `investments` in redux store in addition to `filledDebtOrders`. But they are no longer in `localStorage`. Only `debtOrderReducer.pendingDebtOrders` and `plexReducer.agreeToTerms` are in `localStorage`.

**Comment by chrismin** [comment]
@jmul-dev could you remove the code that puts investments into redux store?  We're working on storing investments in redux store in a separate ticket but in a slightly different way!

**Comment by jmul-dev** [comment]
Oops sorry about that. Will remove investments from redux store.

**Comment by jmul-dev** [comment]
@chrismin done!

**Pull request merged**
