### PR TITLE
Add cancel button for open debt orders

### PR DESCRIPTION
**Pull request by jmul-dev**
This PR introduces the following changes:

- Display Cancel button on pending debt orders
- Toggle delete confirmation modal when Cancel button is clicked
- Display success Toast on success cancellation

### CODE REVIEW

**Comment by jmul-dev** [comment]
screen shot 2018-04-04 at 5 35 13 pm

**Comment by jmul-dev** [comment]
screen shot 2018-04-04 at 5 35 26 pm

**Comment by jmul-dev** [comment]
screen shot 2018-04-04 at 5 35 34 pm

**Comment by nadavhollander** [comment]
There's more to cancellation than just removing the order from local storage -- in Dharma, orders can be "cancelled" in the dharma smart contracts, so as to prevent them from being filled in the future.

The way you can do that in the dharma apis is with the `dharma.order.cancelOrderAsync(debtOrder)` method.

**Comment by jmul-dev** [comment]
This is done.

**Pull request merged**
